* $\Sigma$ is symmetric and positive semi-definite, so its eigenvectors are orthonormal to each other and all of its eigenvalues are nonnegative.
* Performing eigendecomposition

$$X^{T}\Sigma X = X^{T}Q\Lambda Q^{T}X$$

* $X^{T}\Sigma X = \sum_{k} \lambda_{k}{<X, q_{k}>}^{2}$
* Note that, $\sum_{k}{<X, q_{k}>}^{2} = X^{T}QQ^{T}x=<X,X>=||X||^{2}$
* Therefor, $\lambda_{\text{min}}||X||^{2} \le X^{T}\Sigma X \le \lambda_{\text{max}}||X||^{2}$
* In the case of $\Sigma^{-1}$, we can do the similar way, since

$$X^{T}\Sigma^{-1} X=Q\Lambda^{-1}Q^{T}=Qdiag(1/\lambda_{\text{max}}, ..., 1/\lambda_{\text{min}})Q^{T}$$


In [6]:
from scipy import linalg
L = linalg.cholesky(hyp["null"]["K"])

In [8]:
L.shape

(100, 100)

In [92]:
import GPy
# import gpflow
import numpy as np

from scipy.linalg import solve_triangular, cholesky

def compute_quad(X, K):
    return np.matmul(np.matmul(np.transpose(X), K), X)

kernel =  GPy.kern.RBF(input_dim = 1) # default setting
# kernel = gpr
varaince = 1.
N = 10 # 100
t = int(0.5 * N)

T = np.linspace(0.,0.1 * N, N)
T = T.reshape((-1,1))

mu = np.zeros((N))

hyp = {"null":{}, "alter":{}}

K1 = kernel.K(T, T) + np.eye(T.shape[0]) * varaince
# assume very simple case: same kernel with same parameters
K2 = np.zeros((N, N))
K2[:t, :t] = K1[:t, :t]
K2[t:, t:] = K1[t:, t:]

hyp["null"]["K"] = K1
hyp["null"]["K_inv"] = np.linalg.inv(K1)
#hyp["null"]["K_inv"] = np.linalge()
hyp["alter"]["K"] = K2

Xs = np.random.multivariate_normal(mu, hyp["alter"]["K"], 10)

# for X in Xs:
    








In [98]:
np.log(np.linalg.det(K1))

2.967008070030671

In [111]:
2 * sum(np.log(L.diagonal()))

2.967008070030671

In [106]:
L = cholesky(K1)
log_det = sum(np.log(L.diagonal())) # np.sum(np.log(L))
log_det 


2.967008070030671

In [35]:
compute_quad(X,K1)

4739.0815861783885

In [95]:
X = Xs[5]

In [21]:
from scipy.linalg import solve_triangular, cholesky

In [65]:
np.sum(L)

100.0

In [71]:
L

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [79]:
L.logdet()

AttributeError: 'numpy.ndarray' object has no attribute 'logdet'

In [82]:
sum(np.log(L.diagonal()))

0.0

In [112]:
L = cholesky(K1)

D = solve_triangular(L, X, lower=True)
alpha = solve_triangular(np.transpose(L), D, lower=True)
quad = np.matmul(np.transpose(X), alpha)

log_det = 2 * sum(np.log(L.diagonal())) # np.sum(np.log(L))


# A = solve_triangular()

2.967008070030671

In [40]:
np.matmul(np.transpose(X), alpha)

146.1638841106889

In [38]:
D1

array([ 0.75826004,  1.49387011,  0.76387499,  1.13571873,  2.93391838,
        2.01347959,  0.52682406,  1.5723635 ,  0.94024099,  0.8845811 ,
        1.86813836,  2.84966823,  4.46866631,  2.52426265,  1.15702436,
        2.44399854,  1.311164  ,  0.25931507,  2.46268564,  0.82977947,
        0.95596839, -0.10810316,  0.8791161 ,  0.94889961, -0.38236488,
        0.67040627,  1.02896761,  0.66894605,  1.57892375,  1.75279935,
        1.21402516,  0.56313962,  0.47513514, -0.44723275, -0.35188208,
       -0.04579759,  2.21198755,  1.1462277 ,  3.03674126,  1.48043629,
        1.32071858,  2.07826024,  2.12273468,  1.5211922 ,  3.17769498,
        1.45113946,  0.08525222,  0.91683869, -1.02353728,  1.8255661 ,
       -0.75930707, -0.96859619, -1.62915841, -2.18708433, -2.65926238,
       -2.83769885, -2.59473067, -2.59839885, -1.41839263, -0.31888568,
       -2.42948552, -2.14040952, -0.90003599, -2.14267228, -2.05172787,
       -2.29011713, -2.23989517, -1.8506834 , -0.5387231 , -2.14

In [23]:
L

array([[1.41421356e+00, 7.03508647e-01, 6.92823729e-01, ...,
        1.00753757e-21, 3.72586092e-22, 1.36383210e-22],
       [0.00000000e+00, 1.22681522e+00, 4.13675978e-01, ...,
        2.53109037e-21, 9.47783933e-22, 3.51291320e-22],
       [0.00000000e+00, 0.00000000e+00, 1.16140754e+00, ...,
        7.19839464e-21, 2.72409086e-21, 1.02036792e-21],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.10348730e+00, 2.15348545e-01, 2.30497095e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.10348730e+00, 2.15348545e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.10348730e+00]])

In [12]:
A = solve_triangular(L, Kxlower=True)

(100, 100)

In [20]:
from scipy import linalg

In [ ]:
linalg.cholesky

In [ ]:
scipy.linalg.solve_triangular

In [21]:
X.shape

(100, 1)

In [19]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])